### ISSUE TITLE
Offset undefined

### ISSUE THREAD

**Issue by wuilmerj24** [Akylas/nativescript-canvas#17]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?
Huawei p smart 2018 android 9

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)=6.2.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
tns-core-modules@6.2.3
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
"tns-ios": {
      "version": "6.2.0"
    },
    "tns-android": {
      "version": "6.2.0"
    }
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "^2.2.1",
    "nativescript-angular": "~8.20.0",
    "nativescript-canvas": "^3.0.0",
    "nativescript-pager": "^12.0.0-alpha.8",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.2.0",
    "tns-platform-declarations": "^6.5.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "^8.3.26",
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^1.0.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.3.0",
    "node-sass": "^4.14.1",
    "sass": "^1.26.5",
    "typescript": "~3.5.3"
  },
### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
`const path=new Path(); path.offset(10,50,path);`

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
### Problem 
When trying to get the offset I pass the parameters but it returns undefined.

**Comment by farfromrefug** [comment]
@wuilmerj24 could you please really fill the issue template?
Almost impossible to understand like that.
And describe ....

**Comment by wuilmerj24** [comment]
@farfromrefug sorry.

**Comment by farfromrefug** [comment]
It is not meant to return anything. Please look a the android documentation

**Comment by wuilmerj24** [comment]
@farfromrefug If I could already read the information. Thank you and I'm sorry.
