### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by erjdriver** [Akylas/nativescript-canvas#18]
I work with nativescript core /ts. Looking the the source code I was able to get draw to work

```
let canvas = page.getViewById("canvas");

    canvas.on( "draw", (data: any) =>
    {) );
```

Is this the correct way?

Any documentation on the API?

Does this plugin work for ios also?

**Comment by farfromrefug** [comment]
Look at the demo app. Everything you need is there

**Comment by erjdriver** [comment]
I didn't see any samples for NS core usage.

Is my usage - i.e. listening to the draw event the correct way.

I have high hopes of this plugin for my app.

Thanks.

**Comment by farfromrefug** [comment]
@erjdriver i wont support NS core as it might not be there in the future. Anyway translating it from the vue demo should be easy. I ll let you look at it.

**Comment by erjdriver** [comment]
I did  look at your examples folder and I didn't see any code working with fonts.

I looked at the api and can set font-family.

but nothing where you can set the size.
