### ISSUE TITLE
drawText bug in ios

### ISSUE THREAD

**Issue by erjdriver** [Akylas/nativescript-canvas#19]
`canvas.drawText( "Hello", 2, 4, 200, 300, paint );`

The ios version of the plugin - doesn't respect the start and end indexes.

Also, the font on the Android version is very small.

Is there a way to standardize the font size across both platforms - e.g. make it dependent on dpi.

**Comment by farfromrefug** [comment]
So for the x y yes not implemented yet on ios. For the font size if you specify it on the paint it will be the same on both platforms

**Comment by farfromrefug** [comment]
I ll close this as I will implement it at one point but for now simply do substr first
