### ISSUE TITLE
Android draw size - Pixel ratio 

### ISSUE THREAD

**Issue by otis78** [Akylas/nativescript-canvas#2]
### Which platform(s) does your issue occur on?
- Both
- iOS:10.1 / Android:8.1
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.0
- Cross-platform modules: 5.2.0 - NativeScript + Angular
- Runtime(s): tns-android: 5.2.0 and tns-ios: 5.2.0
- Plugin(s): 1.0.3
- 

### Please, tell us how to recreate the issue in as much detail as possible.   
This si my onDraw code:

    `onDraw(event: { canvas: Canvas }) {
        const canvas = <Canvas>event.canvas;
      
        const bgPaint = new Paint();
        bgPaint.setColor(new Color(255, 255, 0, 0));
        bgPaint.strokeWidth = 10;
        canvas.drawRect(this.createRect(0, 0, 99 , 99 ), bgPaint);
        bgPaint.setStyle(Style.STROKE);
        bgPaint.setColor(new Color(255, 0, 255, 0));
        canvas.drawRect(this.createRect(10, 10, 80, 80), bgPaint);
    }`

Running the App in both emulator you can se the diffent size in Android. As a reference I draw below of the CanvasView a simple label with the expected size (100x100dp). Se the attached screenshot.

thanks
<img width="1023" alt="screenshot 2019-02-25 at 10 20 06" src="https://user-images.githubusercontent.com/9464429/53327456-207ad600-38e8-11e9-961f-02f87b163636.png">

**Comment by otis78** [comment]
I think this issue is due to the pixel ratio. I logged the canvas size and i see that the the real size in pixel in my case is 263x263px equivalent to 100x100dp.  I am drawing expecting that the conversion from dp to pixel is done by your plugin but to have the correct draw size I have to multiply every value for the display density (utils.layout.getDisplayDensity()). It this expected?

**Comment by farfromrefug** [comment]
@otis78 thanks for the example. Will fix this today. What is the android simulated device?

**Comment by otis78** [comment]
It is a Pixel 2 API 27

**Comment by farfromrefug** [comment]
@otis78 btw can you share the full sample app? or at list the page template

**Comment by otis78** [comment]
Sure, see the attachment
[demo-angular.zip](https://github.com/Akylas/nativescript-canvas/files/2901129/demo-angular.zip)

**Comment by farfromrefug** [comment]
@otis78 should be fixed in 1.0.4

**Comment by otis78** [comment]
Thanks @farfromrefug. It works. 
The only difference about this issue is the different value returned by the canvas methods getWidth and getHeight.
iOS returns the values in dp (in my example 100x100). Android returns the values in pixels that in my example is 263x263. 
It would be better to uniform this values. What do you think about this?

**Comment by farfromrefug** [comment]
@otis78 will do

**Comment by farfromrefug** [comment]
@otis78 should be fixed in 1.0.5

**Comment by otis78** [comment]
Hi @farfromrefug. There is a lot of decimals but it works.

**Comment by farfromrefug** [comment]
@otis78 hadn't any here. Will look at one point
