### ISSUE TITLE
iOS renders bitmaps flipped vertically

### ISSUE THREAD

**Issue by I-NOZex** [Akylas/nativescript-canvas#5]
### Which platform(s) does your issue occur on?
- iOS
- iPhone 6 - iOS 10.0 **SIMULATOR**

### Please, provide the following version numbers that your issue occurs with:

- CLI: **5.4.0**
- Cross-platform modules: **5.4.2**
- Runtime(s):  **tns-ios 5.4.1**
- Plugin(s): 

> **Dependencies:**
> 
> | Plugin  | Version |
> |---|---|
> | nativescript-canvas     | ^2.1.5  |
> | nativescript-theme-core | ~1.0.4  |
> | nativescript-vue        | ~2.2.0  |
> | tns-core-modules        | ~5.4.0  |
> 
> **Dev Dependencies:**
> 
> | Plugin                             | Version |
> |------------------------------------|---------|
> | @babel/core                        | ~7.1.0  |
> | @babel/preset-env                  | ~7.1.0  |
> | babel-loader                       | ~8.0.0  |
> | nativescript-dev-webpack           | ~0.24.0 |
> | nativescript-vue-template-compiler | ~2.2.0  |
> | node-sass                          | ^4.7.1  |
> | vue-loader                         | ~15.4.0 |

### Please, tell us how to recreate the issue in as much detail as possible. 

- Create new **VUE** project using `tns create`
- run on terminal `tns plugin add nativescript-canvas`
- Use this Vue page component: [pastbin](https://pastebin.com/TCVD9exA)
- run the project **`tns run ios --emulator`**
- bitmaps are rendered upside down

**Comment by farfromrefug** [comment]
@I-NOZex Thanks will fix it right away!

**Comment by farfromrefug** [comment]
@I-NOZex fixed in 2.1.6

**Comment by I-NOZex** [comment]
how that's fast mate! 😅 thank you! gonna update and test :)

**Comment by I-NOZex** [comment]
Now it's correct, but it seems that the Y axis is reversed.
That means if I want to render the image at **x: 0, y: 50**, the image is rendered as if I defined **y: -50**

**Y = 50**
![y50](https://user-images.githubusercontent.com/5805207/59367094-b9204f00-8d3b-11e9-9707-4af847611d52.PNG)

**Y = -50
![y-50](https://user-images.githubusercontent.com/5805207/59367115-c5a4a780-8d3b-11e9-869f-21cab91772f8.PNG)
**

**Comment by farfromrefug** [comment]
@I-NOZex  OK let me think a bit about this

**Comment by farfromrefug** [comment]
@I-NOZex fixed in 2.1.7

**Comment by I-NOZex** [comment]
I'm sorry, the issue persists :(
