### ISSUE TITLE
README.md needs a correction

### ISSUE THREAD

**Issue by boguszjelinski** [Akylas/nativescript-canvas#7]
1) In the "NativeScript + Angular" paragraph of README there is an apostrophe missing in the CanvasView tag after draw($event). Not a problem for anyone, I guess, but it might degrade the first impression.
2) I get "Cannot find name 'canvas'.ts(2304)" unless I write event.canvas.drawRect
all this with tns v. 5.4.2 and HelloWorld template with Angular. 

I can now see a rectangle in the emulator (with "tns run android --emulator") although I get en error in the command line:
ERROR in node_modules/nativescript-canvas/canvas.d.ts(145,26): error TS2304: Cannot find name 'android'.

Here you might need some more versions: 
node.js is 10.15.0
tns-android: 5.4.0
 "nativescript-angular": "~8.0.0",
 "nativescript-canvas": "^2.1.8",

**Comment by farfromrefug** [comment]
@boguszjelinski i will update the Readme.
For your android issue, add ```tns-platform-declarations``` this will fix the issue for now.
I need to rewrite the typings completely which is really long
